name: macroEnsemble Blog
markdown: kramdown
highlighter: pygments
relative_permalinks: false
gauges_id: 503c5af6613f5d0f19000027
permalink: pretty
excerpt_separator: noifniof3nioaniof3nioafafinoafnoif
repository: https://github.com/xinchoubiology
baseurl: http://xinchoubiology.github.io/macroEnsemble

